CREATE TABLE Devices (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255),
	Port VARCHAR(100)
);

CREATE TABLE Settings (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DeviceId INT NOT NULL,
	HumidityTrigger INT,
	
	FOREIGN KEY (DeviceId) REFERENCES Devices(Id)
);

CREATE TABLE Schedules (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DeviceId INT NOT NULL,
	Time VARCHAR(10),
	
	FOREIGN KEY (DeviceId) REFERENCES Devices(Id)
);